apiVersion: v2
name: helm-demo
description: A Helm chart for the SafeHarbor Demo Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - demo
  - safeharbor
  - http-echo
maintainers:
  - name: SafeHarbor Team
