apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-demo.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "helm-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "helm-demo.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.service.sessionAffinity "ClientIP" }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  {{- end }}
