---
name: CI - Pull request title format check

on:
  # pull_request:
  #   types: [opened, edited, synchronize]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-title-check:
    name: Validate PR title format
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          scopes: |
            JIRA-[0-9]+
            deps
            deps-dev
            changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}
...